collection_name: agent
persis_director: chroma_db
k: 3
data_path: data
md5_hex_store: md5.text
allow_knowledge_file_type: ['txt','pdf']

chunk_size: 200
chunk_overlap: 20
separators: ["\n\n", "\n", ".",", "!", "?", "ã€‚", "!"","?","","""""]

