[project]
name = "myfastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.8",
    "pydantic>=2.12.5",
    "python-multipart>=0.0.22",
    "typing>=3.10.0.0",
    "uvicorn>=0.40.0",
]
